image:
  name: maven:3.8-openjdk-17

stages:
  - build
  - test
  - deploy

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -U -DskipTests clean compile"
  tags:
    - docker

maven-test:
  stage: test
  environment: staging
  script:
    - "mvn -U test"
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit:
        - "**/surefire-reports/*.xml"
  tags:
    - docker


maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn -U deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
    - /^dev$/
    - /^ft-.*-deploy$/
    - /^rl-.*$/
    - /^hf-.*$/
  tags:
    - docker
